### PR TITLE
Add libffi as dependency

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- https://github.com/riboseinc/homebrew-metanorma/issues/4

### CODE REVIEW

**Comment by ronaldtse** [comment]
Notice that libffi is a keg-only formula.

```
==> Downloading https://homebrew.bintray.com/bottles/libffi-3.2.1.mojave.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libffi-3.2.1.mojave.bottle.tar.gz
==> Caveats
libffi is keg-only, which means it was not symlinked into /usr/local,
because some formulae require a newer version of libffi.

For compilers to find libffi you may need to set:
  export LDFLAGS="-L/usr/local/opt/libffi/lib"

For pkg-config to find libffi you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
```

To only test a branch PR directly install it from the formula:

```
brew install https://raw.githubusercontent.com/riboseinc/homebrew-metanorma/c253f0040dd31c2383aee147257ec798c1db67f2/Formula/metanorma.rb
```

**Comment by ronaldtse** [comment]
It's running right now.

**Comment by ronaldtse** [comment]
@CAMOBAP795 same error for me...

**Comment by CAMOBAP795** [comment]
@ronaldtse may I ask you to zip /usr/local/Cellar/metanorma/1.1.0/libexec/gems/ffi-1.9.25 from your mac and sent it to me?

**Comment by CAMOBAP795** [comment]
I have some assumption could you please try install updated file `brew install https://raw.githubusercontent.com/riboseinc/homebrew-metanorma/8ee80f23c96c39d26358e3db9e339f66de6f5b0b/Formula/metanorma.rb`

**Comment by ronaldtse** [comment]
It worked!!

**Comment by ronaldtse** [comment]
Let's wait until Travis passes too 👍

**Comment by CAMOBAP795** [comment]
@ronaldtse PR is ready, may I ask you to check again
`https://raw.githubusercontent.com/riboseinc/homebrew-metanorma/9bc88f0f080ac621eaab36ad74df4f73eec6f519/Formula/metanorma.rb`

**Comment by CAMOBAP795** [comment]
@ronaldtse could you please attach `/usr/local/Cellar/metanorma/1.1.0/libexec/extensions/universal-darwin-18/2.3.0/nokogiri-1.8.5/mkmf.log` or `/usr/local/Cellar/metanorma/1.1.0/libexec/extensions/universal-darwin-18/2.3.0/nokogiri-1.8.5/gem_make.out`

**Comment by ronaldtse** [comment]
Both attached.
[mkmf.log](https://github.com/riboseinc/homebrew-metanorma/files/2785775/mkmf.log)

[gem_make.out.zip](https://github.com/riboseinc/homebrew-metanorma/files/2785778/gem_make.out.zip)

**Comment by CAMOBAP795** [comment]
@ronaldtse may I ask you to run `file /usr/lib/libiconv*.dylib`

**Comment by ronaldtse** [comment]
```
/usr/lib/libiconv.2.4.0.dylib: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit dynamically linked shared library x86_64] [i386]
/usr/lib/libiconv.2.4.0.dylib (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
/usr/lib/libiconv.2.4.0.dylib (for architecture i386):	Mach-O dynamically linked shared library i386
/usr/lib/libiconv.2.dylib:     Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit dynamically linked shared library x86_64] [i386]
/usr/lib/libiconv.2.dylib (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
/usr/lib/libiconv.2.dylib (for architecture i386):	Mach-O dynamically linked shared library i386
/usr/lib/libiconv.dylib:       Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit dynamically linked shared library x86_64] [i386]
/usr/lib/libiconv.dylib (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
/usr/lib/libiconv.dylib (for architecture i386):	Mach-O dynamically linked shared library i386

```

**Comment by CAMOBAP795** [comment]
@ronaldtse hmm, I going back to previous working solution, I'm not very happy about it but I don't wanna bother you again

Please check `brew install -vd https://raw.githubusercontent.com/riboseinc/homebrew-metanorma/5184adffc997720aa25f6913cc386b766a8b5092/Formula/metanorma.rb`

**Comment by ronaldtse** [comment]
It worked!!

**Comment by CAMOBAP795** [comment]
@ronaldtse I propose wait for CI and merge once it passed

**Comment by ronaldtse** [comment]
Thank you @CAMOBAP795 !

**Pull request merged**
