### PR TITLE
Add dependency section

### PR DESCRIPTION
**Pull request by CAMOBAP795**
Before merge:
 - [x] Wait for https://github.com/riboseinc/metanorma-cli/pull/20 merge
 - [x] Wait for https://github.com/riboseinc/metanorma-cli/pull/20 release
 - [x] Update URL & sha256 after release of metanorma-cli

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP795 the first SHA is the SHA of the tar.gz. The "bottle" SHA is the SHA of the re-built gem under Mojave.

**Comment by CAMOBAP795** [comment]
@ronaldtse yep I have did it but in separate commit, looking why it still report outdated SHA

**Comment by ronaldtse** [comment]
@CAMOBAP795 for the second SHA, you need to do:

```sh
wget https://github.com/riboseinc/metanorma-cli/archive/v1.1.0.tar.gz
tar -zxvf v1.1.0.tar.gz
cd metanorma-cli-1.1.0/
gem build metanorma-cli.gemspec
shasum -a 256 metanorma-cli-1.1.0.gem 
```

The output is:
```
a44cf568b40203fed26d7538c26bd41dc71806486fbf75b679a6bef1257e8d73  metanorma-cli-1.1.0.gem
```

Which means the "bottle SHA" for Mojave (I'm on Mojave) should be `a44cf568b40203fed26d7538c26bd41dc71806486fbf75b679a6bef1257e8d73`.

**Comment by CAMOBAP795** [comment]
@ronaldtse I'm on Mojave too but cannot get consistent sha256, after each `gem build metanorma-cli.gemspec` it changes, investigation in progress

**Comment by ronaldtse** [comment]
I think PlantUML should be mandatory. The formula structure comes from the “asciidoctor” gem formula, perhaps you can copy that into this PR and try out how it works?

**Comment by ronaldtse** [comment]
@CAMOBAP795 is this working now?

**Comment by CAMOBAP795** [comment]
@ronaldtse not yet still working on it

**Comment by ronaldtse** [comment]
@CAMOBAP795 good idea, can you help create a puppeteer formula then?

**Comment by CAMOBAP795** [comment]
@ronaldtse I have some progress, I would say %80 ready, I have found solution with `resource` so we don't need to publish `puppeteer` brew package anymore, but now we have issue with execution `install_name_tool` working on it right now

**Comment by ronaldtse** [comment]
@CAMOBAP795 is this to be merged soon? Thanks

**Comment by CAMOBAP795** [comment]
@ronaldtse unfortunately no, I understand the problem, the only solution which I know is to recompile Chrome Framework, but this absolutely overkill, so I looking for another solution

Unfortunately I cannot give you more visibility when it will be done

**Comment by CAMOBAP795** [comment]
Probably https://www.rubydoc.info/github/Homebrew/brew/Formula.pour_bottle%3F can help, investigation in progress

**Comment by CAMOBAP795** [comment]
> @CAMOBAP795 why can't we use a formula like this to setup puppeteer? 

We already have done it exactly the same way but with `resource`, and if you will have look at logs it installs successfully, it becomes broken, when brew try to modify native library lookup path in libEGL.dylib

BTW thanks for link i see there `install_symlink` instead `install`, maybe this will help, PR updated

**Comment by ronaldtse** [comment]
@CAMOBAP795 and does this work locally? If the problem is Travis, we can always merge this first?

**Comment by CAMOBAP795** [comment]
> However, it looks like the paths can't even find 'puppeteer', it's not because of the dylib error. Maybe we have to provide $NODE_PATH?

we had it before, right now I'm experimenting and disabled Chormioum installation this is why you dont see it here is example of past build with dynlib issue https://travis-ci.com/riboseinc/homebrew-metanorma/builds/96398336

But right now we have problem with node_module lookup too, working on it 

> and does this work locally? If the problem is Travis, we can always merge this first?

Locally we also have a problem, I did several commit to add right formula testing commands

**Comment by CAMOBAP795** [comment]
@ronaldtse Finally I have found solution let me summarize that avoid 'Failed changing dylib ID of' issue, there is complex workaround was applied. 

To make it work we need to merge https://github.com/riboseinc/metanorma/pull/36 to allow override NODE_PATH from environment which call the script, please review it carefully because tests broken IDK why but I can have a look, just let me know

Also I have posted topic on https://discourse.brew.sh/t/how-to-prevent-dylib-from-linkage-fixing/3843 to find much simpler solution

**Comment by ronaldtse** [comment]
Thank you @CAMOBAP795 !

@opoudjis can you please help review the spec failure at 
https://github.com/riboseinc/metanorma/pull/36 (specifically 
https://github.com/riboseinc/metanorma/pull/36#issuecomment-453185728)?

Once @opoudjis gives the OK we can proceed.

**Comment by CAMOBAP795** [comment]
@ronaldtse hm but we need to have a new release or metanorma (which will include this PR https://github.com/riboseinc/metanorma/pull/36) as I see it's not approved merged yet

**Comment by CAMOBAP795** [comment]
@ronaldtse I have added `sed` command to update `metanorma-standoc` version in gemspec, now `puppeteer` npm module works but looks like we found another problem

https://travis-ci.com/riboseinc/homebrew-metanorma/builds/97659143

```
/usr/local/Cellar/metanorma/1.1.0/bin/metanorma --type csd /private/tmp/metanorma-test-20190117-3457-dui9h7/test-csd.adoc
...
net::ERR_FILE_NOT_FOUND at file:///private/tmp/metanorma-test-20190117-3457-dui9h7//private/tmp/metanorma-test-20190117-3457-dui9h7/test-csd.pdf.html
```

As you may see `file:///private/tmp/metanorma-test-20190117-3457-dui9h7//private/tmp/metanorma-test-20190117-3457-dui9h7/test-csd.pdf.html` looks ugly

I have tested it locally and reproduced the same issue: when we run `metanorma` with `--type csd` outside directory where `adoc` file  placed, we have this problem

Here we have solution solution
1. Skip test `metanorma --type csd` and release of `metanorma-cli` with updated `metanorma-standoc` and proceed with release oh honeycomb
2. Investigate `metanorma --type csd` issue and postpone `homebrew-metanorma` release

@ronaldtse how do you think?

**Comment by ronaldtse** [comment]
@CAMOBAP795 let's do Option 1.

@opoudjis could you help fix the stated `metanorma-csd` issue ("when we run metanorma with --type csd outside directory where adoc file placed", it cannot generate the output)?

**Comment by CAMOBAP795** [comment]
@ronaldtse got it, if @opoudjis busy, I can help with this issue too (after this PR) just let me know

**Comment by ronaldtse** [comment]
@CAMOBAP795 that'd be great, yes @opoudjis is probably busy...

**Comment by CAMOBAP795** [comment]
@ronaldtse this PR is ready to merge I need write access to `riboseinc/homebrew-core` because for now I have: 
 - `ERROR: Permission to riboseinc/homebrew-core.git denied to CAMOBAP795.`

Also https://github.com/riboseinc/metanorma/issues/37 created

**Comment by ronaldtse** [comment]
@CAMOBAP795 actually we don’t use the homebrew-core fork, that is for merging into official homebrew. 

The way to use this formula is through “brew tap riboseinc/metanorma” then “brew install metanorma”.

So I think we’re all done here. Thanks!!

**Comment by CAMOBAP795** [comment]
@ronaldtse thanks for clarification, in that case you are right, I moving to https://github.com/riboseinc/metanorma/issues/37

**Comment by opoudjis** [comment]
Request to you both @ronaldtse and @CAMOBAP795 to add issues explicitly and assign them to me; I notice them before I notice notifications.

**Comment by opoudjis** [comment]
https://github.com/riboseinc/metanorma/issues/37 fixed

**Pull request merged**
